---
abstract: 'Skryf application'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  List::Util: 0
  Mojolicious: 0
  Test::Mojo: 0
  Test::More: 0
  Test::NoTabs: 0
  lib: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Skryf
requires:
  App::cpanminus: 0
  Carp: 0
  Class::Load: 0
  DateTime: 0
  DateTime::Format::RFC3339: 0
  Encode: 0
  File::Copy::Recursive: 0
  File::ShareDir: 0
  File::chdir: 0
  FindBin: 0
  IO::Prompt: 0
  Mango: 0
  Mojo::Base: 0
  Mojo::JSON: 0
  Mojo::Template: 0
  Mojo::UserAgent: 0
  Mojo::Util: 0
  Path::Tiny: 0
  Skryf::Model::Blog: 0
  String::Dirify: 0
  String::Util: 0
  Text::MultiMarkdown: 0
  XML::Atom::SimpleFeed: 0
  constant: 0
  feature: 0
  version: 0
version: 1.0.3
