package App::skryf::Manual::Plugins::Developing;

our $VERSION = '0.99_1';

1;

__END__

=pod

=encoding UTF-8

=for :stopwords Adam Stokes

=head1 NAME

App::skryf::Manual::Plugins::Developing - A guide to writing Plugins for Skryf

=head1 PLUGIN METADATA

The plugin metadata allows the exposure of certain capabilities.

=head2 plugin_rest

  has plugin_rest => 1;

Plugin exposes a RESTful interface

=head2 plugin_rest_public

  has plugin_rest_public => 1;

The exposed RESTful interface is for public consumption

=head2 plugin_rest_version

  has plugin_rest_version => '1.0';

The REST interface api version

=head2 template_files

  has template_files => qw[index new edit detail];

The template files used for rendering of content. These filename would match whatever your theme has, for example, L<App::skryf::Theme::Booshka> contains a sub-directory within its theme with the following layout:

  templates/
       blog/
            index.html.ep
            new.html.ep
            edit.html.ep
            detail.html.ep

Take a look at the L<App::skryf::Manual::Themes::Developing> documentation for more info.

=head1 SEE ALSO

L<App::skryf::Manual::Plugins>

L<App::skryf::Manual::Plugins::Using>

=head1 AUTHOR

Adam Stokes <adamjs@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013-2014 by Adam Stokes.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
