package App::skryf::Manual::Plugins;

our $VERSION = '0.99_1';

1;

__END__

=pod

=encoding UTF-8

=for :stopwords Adam Stokes

=head1 NAME

App::skryf::Manual::Plugins - A guide to using and developing plugins

=head1 SEE ALSO

L<App::skryf::Manual::Plugins::Developing>

L<App::skryf::Manual::Plugins::Using>

=head1 AUTHOR

Adam Stokes <adamjs@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013-2014 by Adam Stokes.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
