requires 'Mango', '0.24';
requires 'Mojolicious::Plugin::Gravatar';
requires 'Mojolicious::Plugin::GoogleAnalytics';
requires 'Mojolicious::Plugin::Disqus::Tiny';

on test => sub {
    requires 'Test::More';
    requires 'Test::Mojo';
};

on build => sub {
    requires 'Test::More';
    requires 'Test::Mojo';
};
