use Rex::Lang::Perl::Perlbrew;
use Rex::Commands::Rsync;

use constant PERLV => 5.18.1;

die "No environment set." unless $ENV{BLOGUSER};

set perlbrew => root => "/home/$ENV{BLOGUSER}/perl5/perlbrew";

user $ENV{BLOGUSER} || "skryf";

group webserver => $ENV{BLOGSERVER};

desc "Restart blog service";
task "restart",
  group => "webserver",
  sub {
    perlbrew -use => PERLV;
    say "Restarting blog";
    run "ubic restart stokesblog";
  };

desc "Does a full software upgrade and dependency check";
task "upgrade",
  group => "webserver",
  sub {
    perlbrew -use => PERLV;
    say "cpan update";
    run "cpanm -q --notest App::skryf";
    do_task "restart";
  };
