#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

require Mojolicious::Commands;
Mojolicious::Commands->start_app('App::skryf');

__END__

=head1 NAME

App-skryf - Perl CMS/CMF.

=head1 DESCRIPTION

CMS/CMF platform for Perl.

=head1 PREREQS

L<https://github.com/tokuhirom/plenv/>.

=head1 INSTALLATION (BLEEDING EDGE)

    $ cpanm https://github.com/skryf/App-skryf.git

=head1 SETUP

    $ skryf setup

=head2 Themes

Themes are installed via cpan, e.g:

    $ cpanm https://github.com/skryf/App-skryf-Theme-Booshka.git

Then specify the theme in your config:

    theme => 'Booshka'

=head2 Plugins

Plugins are installed via cpan, e.g:

    $ cpanm https://github.com/skryf/App-skryf-Plugin-Blog.git

Then specify plugin in your config:

    extra_modules => { 'Blog' => 1 }

A list of supported/tested plugins for Skryf can be found at L<https://github.com/skryf>

=head1 RUN (Development)

    $ skryf daemon

=head1 RUN (Production)

I use Ubic to manage the process

     use Ubic::Service::SimpleDaemon;
     my $service = Ubic::Service::SimpleDaemon->new(
      bin => "hypnotoad -f `which skryf`",
      cwd => "/home/username",
      stdout => "/tmp/blog.log",
      stderr => "/tmp/blog.err.log",
      ubic_log => "/tmp/blog.ubic.log",
      user => "username"
     );

=head1 AUTHOR

Adam Stokes E<lt>adamjs@cpan.orgE<gt>

=head1 COPYRIGHT

Copyright 2013-2014 Adam Stokes

=head1 LICENSE

Licensed under the same terms as Perl.

=cut
