#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use Mojolicious::Commands;
my $commands = Mojolicious::Commands->new;
push @{$commands->namespaces}, 'Skryf::Command';
$commands->run(@ARGV);

__END__

=head1 NAME

Skryf - Perl on web.

=head1 DESCRIPTION

Perl on web, easy does it web development.

=head1 INSTALLATION

    $ cpanm git@github.com:skryf/Skryf.git

=head1 SETUP

    $ skryf new

=head2 Themes

Themes are installed via carton and a cpanfile, in your B<cpanfile> add the following:

    requires 'Skryf::Theme::Booshka', '0', git => 'git@github.com:skryf/Skryf-Theme-Booshka.git';
    $ carton install

Then specify the theme in your config:

    theme => 'Booshka'

=head2 Plugins

Plugins are installed via carton and a cpanfile, in your B<cpanfile> add the following:

    requires 'Skryf::Plugin::Blog', '0', git => 'git@github.com:skryf/Skryf-Plugin-Blog.git';

Then specify plugin in your config:

    plugins => { 'Blog' => 1 }

A list of supported/tested plugins for Skryf can be found
at L<https://github.com/skryf>

=head1 RUN (Development)

    $ morbo script/app.pl

=head1 RUN (Production)

I use Ubic to manage the process

     use Ubic::Service::SimpleDaemon;
     my $service = Ubic::Service::SimpleDaemon->new(
      bin => "hypnotoad -f script/app.pl",
      cwd => $ENV{HOME} ."/skryf-application",
      stdout => $ENV{HOME} ."/skryf-application/logs/app.log",
      stderr => $ENV{HOME} ."/skryf-application/logs/app.err.log",
      ubic_log => $ENV{HOME} ."/skryf-application/logs/app.ubic.log",
      user => $ENV{USER}
     );

=head1 AUTHOR

Adam Stokes E<lt>adamjs@cpan.orgE<gt>

=head1 COPYRIGHT

Copyright 2013-2014 Adam Stokes

=head1 LICENSE

Licensed under the same terms as Perl.

=cut
